### ISSUE TITLE
Fails to compile with OpenSSL 1.1

### ISSUE THREAD

**Issue by GLolol** [DALnet/bahamut#23]
```bash
$ make
Building src
make[1]: Entering directory '/home/gl/bahamut-git/src'
gcc -I../include -g -O2 -Wall -fno-strict-aliasing -c dh.c
dh.c: In function ‘dh_start_session’:
dh.c:285:11: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
     si->dh->p = BN_dup(ircd_prime);
           ^~
In file included from ../include/memcount.h:27:0,
                 from dh.c:38:
dh.c: At top level:
../include/h.h:219:21: warning: inline function ‘get_listener_name’ declared but never defined
 extern inline char *get_listener_name(aListener *);
                     ^~~~~~~~~~~~~~~~~
../include/h.h:120:21: warning: inline function ‘finishconf’ declared but never defined
 extern inline char *finishconf(void);
                     ^~~~~~~~~~
Makefile:49: recipe for target 'dh.o' failed
make[1]: *** [dh.o] Error 1
make[1]: Leaving directory '/home/gl/bahamut-git/src'
Building doc
make[1]: Entering directory '/home/gl/bahamut-git/doc'
make[1]: Nothing to be done for 'build'.
make[1]: Leaving directory '/home/gl/bahamut-git/doc'
Building tools
make[1]: Entering directory '/home/gl/bahamut-git/tools'
make[1]: Nothing to be done for 'build'.
make[1]: Leaving directory '/home/gl/bahamut-git/tools'
******************************************************************************
* For help with bahamut, please refer to http://bahamut.dal.net/             *
* If you encouter serious security related bugs, please mail coders@dal.net  *
* For other bug reports and inquiries, please mail dalnet-src@dal.net        *
* Thank you for choosing Bahamut!  - The DALnet coding team                  *
******************************************************************************
```

**Comment by rscs** [comment]
See #27 for a patch/fix for this.
